# Generated by Django 3.1.5 on 2021-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topingredients',
            table='ingredient_app_topingredients',
        ),
    ]
