# Generated by Django 3.1.5 on 2021-02-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AlterModelOptions(
            name='topingredients',
            options={'ordering': ['product_name'], 'verbose_name': 'TopIngredient', 'verbose_name_plural': 'TopIngredients'},
        ),
    ]
